
import React, { useState, useRef, useEffect } from 'react';
import { Helmet } from 'react-helmet';
import { motion } from 'framer-motion';
import { Layers, Type, Image as ImageIcon, Palette, Move, Download, Save, ShoppingCart, Undo, Redo, Trash2, Maximize2, Wand2 } from 'lucide-react';
import { toast } from 'sonner';

import Header from '@/components/Header.jsx';
import Footer from '@/components/Footer.jsx';
import IntegratedAiChat from '@/components/integrated-ai-chat.jsx';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Slider } from "@/components/ui/slider";
import { Badge } from '@/components/ui/badge';

const productMockups = {
  tshirt: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&q=80&w=800",
  hoodie: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&q=80&w=800"
};

const AIDesignerPage = () => {
  const [activeTab, setActiveTab] = useState("chat");
  const [productType, setProductType] = useState("tshirt");
  const [designElements, setDesignElements] = useState([]);
  const [generatedImages, setGeneratedImages] = useState([]); // from AI chat
  
  // Simulated Canvas State
  const [zoom, setZoom] = useState(1);
  const [isSaving, setIsSaving] = useState(false);

  const handleMessagesChange = (messages) => {
    // Extract images generated by AI to show in library
    const images = [];
    messages.forEach(msg => {
      if (msg.role === 'assistant' && msg.images) {
        images.push(...msg.images);
      }
    });
    // Deduplicate
    setGeneratedImages([...new Set(images)]);
  };

  const handleAddGeneratedImage = (url) => {
    setDesignElements(prev => [...prev, { id: Date.now(), type: 'image', url, x: 50, y: 50, scale: 1 }]);
    toast.success("Design added to canvas");
    setActiveTab("layers");
  };

  return (
    <div className="min-h-screen bg-background flex flex-col overflow-hidden">
      <Helmet>
        <title>AI Designer Studio | TioraS Fashions</title>
      </Helmet>
      <Header />

      <main className="flex-1 flex flex-col lg:flex-row h-[calc(100vh-80px)]">
        {/* Left Panel: Tools & AI (30%) */}
        <aside className="w-full lg:w-[400px] xl:w-[450px] bg-card border-r border-border/50 flex flex-col shrink-0 z-10 shadow-[4px_0_24px_rgba(0,0,0,0.02)]">
          <Tabs value={activeTab} onValueChange={setActiveTab} className="flex-1 flex flex-col overflow-hidden">
            <div className="p-2 bg-muted/20 border-b border-border/50">
              <TabsList className="w-full grid grid-cols-5 h-auto bg-transparent gap-1 p-0">
                <TabsTrigger value="chat" className="flex-col gap-1 py-3 px-1 data-[state=active]:bg-background data-[state=active]:shadow-sm rounded-lg"><Wand2 className="w-5 h-5 text-primary" /><span className="text-[10px] font-bold">AI Chat</span></TabsTrigger>
                <TabsTrigger value="text" className="flex-col gap-1 py-3 px-1 data-[state=active]:bg-background data-[state=active]:shadow-sm rounded-lg"><Type className="w-5 h-5" /><span className="text-[10px] font-bold">Text</span></TabsTrigger>
                <TabsTrigger value="graphics" className="flex-col gap-1 py-3 px-1 data-[state=active]:bg-background data-[state=active]:shadow-sm rounded-lg"><ImageIcon className="w-5 h-5" /><span className="text-[10px] font-bold">Graphics</span></TabsTrigger>
                <TabsTrigger value="colors" className="flex-col gap-1 py-3 px-1 data-[state=active]:bg-background data-[state=active]:shadow-sm rounded-lg"><Palette className="w-5 h-5" /><span className="text-[10px] font-bold">Colors</span></TabsTrigger>
                <TabsTrigger value="layers" className="flex-col gap-1 py-3 px-1 data-[state=active]:bg-background data-[state=active]:shadow-sm rounded-lg"><Layers className="w-5 h-5" /><span className="text-[10px] font-bold">Layers</span></TabsTrigger>
              </TabsList>
            </div>

            <div className="flex-1 overflow-y-auto bg-background/50 custom-scrollbar">
              <TabsContent value="chat" className="h-full m-0 border-none outline-none">
                {/* Integrated AI Chat Component */}
                <IntegratedAiChat onMessagesChange={handleMessagesChange} />
              </TabsContent>

              <TabsContent value="text" className="p-6 m-0 space-y-6">
                <h3 className="font-bold text-lg" style={{ fontFamily: 'Playfair Display, serif' }}>Text Elements</h3>
                <div className="space-y-4">
                  <div className="p-4 border border-border/60 rounded-xl bg-card text-center text-muted-foreground border-dashed">
                    <Type className="w-8 h-8 mx-auto mb-2 opacity-50" />
                    <p className="text-sm">Feature coming soon.</p>
                    <p className="text-xs opacity-70">Use AI Chat to generate text designs for now.</p>
                  </div>
                </div>
              </TabsContent>

              <TabsContent value="graphics" className="p-6 m-0 space-y-6">
                <h3 className="font-bold text-lg" style={{ fontFamily: 'Playfair Display, serif' }}>AI Generated Graphics</h3>
                <div className="grid grid-cols-2 gap-3">
                  {generatedImages.length === 0 ? (
                    <div className="col-span-2 text-center p-8 bg-muted/20 rounded-xl border border-border/50 border-dashed text-muted-foreground">
                      <ImageIcon className="w-10 h-10 mx-auto mb-2 opacity-30" />
                      <p className="text-sm">Ask the AI to generate a design, and it will appear here.</p>
                    </div>
                  ) : (
                    generatedImages.map((url, idx) => (
                      <div key={idx} className="relative aspect-square rounded-xl overflow-hidden border border-border/50 group cursor-pointer" onClick={() => handleAddGeneratedImage(url)}>
                        <img src={url} alt="Generated" className="w-full h-full object-cover transition-transform group-hover:scale-105" />
                        <div className="absolute inset-0 bg-primary/80 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                          <span className="text-white text-xs font-bold font-medium tracking-wider">Use Design</span>
                        </div>
                      </div>
                    ))
                  )}
                </div>
              </TabsContent>

              <TabsContent value="colors" className="p-6 m-0 space-y-6">
                 <h3 className="font-bold text-lg" style={{ fontFamily: 'Playfair Display, serif' }}>Product Colors</h3>
                 <div className="flex gap-3 flex-wrap">
                    {['#ffffff', '#000000', '#1E3A8A', '#D4AF37', '#e11d48'].map(color => (
                      <button key={color} className="w-10 h-10 rounded-full border-2 border-border/50 shadow-sm hover:scale-110 transition-transform" style={{ backgroundColor: color }} />
                    ))}
                 </div>
              </TabsContent>

              <TabsContent value="layers" className="p-6 m-0 space-y-4">
                <h3 className="font-bold text-lg flex justify-between items-center" style={{ fontFamily: 'Playfair Display, serif' }}>
                  Layers <Badge variant="secondary">{designElements.length}</Badge>
                </h3>
                {designElements.length === 0 ? (
                  <p className="text-sm text-muted-foreground text-center py-8">No layers yet. Add a design to start.</p>
                ) : (
                  <div className="space-y-2">
                    {designElements.map((el, i) => (
                      <div key={el.id} className="flex items-center justify-between p-3 bg-card border border-border/50 rounded-xl hover:border-primary/30 transition-colors">
                        <div className="flex items-center gap-3">
                          <div className="w-10 h-10 rounded bg-muted overflow-hidden shrink-0">
                            {el.type === 'image' && <img src={el.url} className="w-full h-full object-cover" alt="Layer" />}
                          </div>
                          <span className="font-medium text-sm text-foreground">Layer {i + 1}</span>
                        </div>
                        <button onClick={() => setDesignElements(prev => prev.filter(e => e.id !== el.id))} className="text-muted-foreground hover:text-destructive p-2">
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    ))}
                  </div>
                )}
              </TabsContent>
            </div>
          </Tabs>
        </aside>

        {/* Right Panel: Canvas Area (70%) */}
        <div className="flex-1 flex flex-col bg-muted/10 relative overflow-hidden">
          {/* Top Canvas Bar */}
          <div className="h-14 bg-background border-b border-border/50 flex items-center justify-between px-6 z-10 shadow-sm">
            <div className="flex items-center gap-2 bg-muted/50 p-1 rounded-lg">
              <Button variant="ghost" size="sm" onClick={() => setProductType('tshirt')} className={`rounded-md h-8 text-xs font-bold ${productType === 'tshirt' ? 'bg-background shadow-sm' : ''}`}>T-Shirt</Button>
              <Button variant="ghost" size="sm" onClick={() => setProductType('hoodie')} className={`rounded-md h-8 text-xs font-bold ${productType === 'hoodie' ? 'bg-background shadow-sm' : ''}`}>Hoodie</Button>
            </div>
            <div className="flex items-center gap-4">
              <div className="flex items-center gap-2">
                <span className="text-xs text-muted-foreground font-medium">Zoom</span>
                <Slider defaultValue={[100]} max={200} min={50} step={10} className="w-24" onValueChange={(v) => setZoom(v[0]/100)} />
              </div>
            </div>
          </div>

          {/* Canvas Workspace */}
          <div className="flex-1 overflow-auto p-4 md:p-12 flex items-center justify-center bg-[url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxwYXRoIGQ9Ik0wIDEwaDQwdjFIwMHpNMTkgNDBoMXYtNDBoLTF6IiBmaWxsPSJyZ2JhKDAsMCwwLDAuMDUpIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+')]">
            <motion.div 
              className="relative bg-white shadow-2xl rounded-2xl overflow-hidden transition-transform origin-center"
              style={{ scale: zoom, width: '400px', height: '500px' }}
              layoutId="product-canvas"
            >
              {/* Product Base Image */}
              <img src={productMockups[productType]} alt="Product base" className="w-full h-full object-cover opacity-90" />
              
              {/* Printable Area Guide */}
              <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
                <div className="w-[60%] h-[70%] border-2 border-primary/20 border-dashed rounded-xl" />
              </div>

              {/* Placed Designs */}
              {designElements.map((el) => (
                <motion.div 
                  key={el.id}
                  className="absolute cursor-move"
                  style={{ top: `${el.y}%`, left: `${el.x}%`, x: '-50%', y: '-50%', scale: el.scale }}
                  drag
                  dragMomentum={false}
                >
                  <div className="relative group p-2 border-2 border-transparent hover:border-primary border-dashed rounded-lg">
                     {el.type === 'image' && <img src={el.url} className="w-48 h-auto object-contain mix-blend-multiply" draggable="false" alt="Design" />}
                     {/* Scale handles could go here */}
                  </div>
                </motion.div>
              ))}
            </motion.div>
          </div>

          {/* Bottom Action Bar */}
          <div className="h-20 bg-background border-t border-border/50 flex items-center justify-between px-6 z-10 shadow-[0_-4px_24px_rgba(0,0,0,0.02)]">
            <div className="flex gap-2">
              <Button variant="outline" size="icon" className="rounded-xl border-border/60 hover:bg-muted" title="Undo"><Undo className="w-4 h-4" /></Button>
              <Button variant="outline" size="icon" className="rounded-xl border-border/60 hover:bg-muted" title="Redo"><Redo className="w-4 h-4" /></Button>
              <div className="w-px h-8 bg-border/60 mx-2" />
              <Button variant="ghost" className="text-destructive font-bold rounded-xl hover:bg-destructive/10" onClick={() => setDesignElements([])}>Clear</Button>
            </div>
            
            <div className="flex gap-3">
              <Button variant="outline" className="rounded-xl border-primary/30 text-primary hover:bg-primary/5 shadow-sm font-bold">
                <Download className="w-4 h-4 mr-2" /> Save Draft
              </Button>
              <Button className="rounded-xl gradient-primary text-white shadow-lg font-bold px-6">
                <ShoppingCart className="w-4 h-4 mr-2" /> Complete Design
              </Button>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default AIDesignerPage;
